export const ALL_PRASAD_REQ = "ALL_PRASAD_REQ"; 
export const ALL_PRASAD_SUCCESS = "ALL_PRASAD_SUCCESS";
export const ALL_PRASAD_FAIL = "ALL_PRASAD_FAIL";

export const PRASAD_DETAILS_REQ = "PRASAD_DETAILS_REQ"; 
export const PRASAD_DETAILS_SUCCESS = "PRASAD_DETAILS_SUCCESS";
export const PRASAD_DETAILS_FAIL = "PRASAD_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";